# this is for windows only
# shell:
#   program: Arch

font:
  normal:
    family: "Spleen 32x64"
  italic:
    style: normal
  size: 12
scrolling:
  history: 88888
  multiplier: 3

draw_bold_text_with_bright_colors: false

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  unfocused_hollow: true

live_config_reload: true

mouse:
  hide_when_typing: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: F11, action: ToggleFullscreen  }

window:
  dimensions:
    columns: 124
    lines: 40
  padding:
    x: 5
    y: 4
  #startup_mode: Fullscreen
  startup_mode: Maximized

  # gtk_theme_variant: Dark

colors:
  primary:
    background: '0x505050'
    foreground: '0xdcdccc'
  cursor:
    text: '0x383838'
    cursor: '0xdcdccc'
  normal:
    black:   '0x383838'
    red:     '0xdca3a3'
    green:   '0x5f7f5f'
    yellow:  '0xe0cf9f'
    blue:    '0x7cb8bb'
    magenta: '0xdc8cc3'
    cyan:    '0x93e0e3'
    white:   '0xdcdccc'
  bright:
    black:   '0x6f6f6f'
    red:     '0xdca3a3'
    green:   '0x5f7f5f'
    yellow:  '0xe0cf9f'
    blue:    '0x7cb8bb'
    magenta: '0xdc8cc3'
    cyan:    '0x93e0e3'
    white:   '0xffffff'
  indexed_colors:
    - { index: 16, color: '0xdfaf8f' }
    - { index: 17, color: '0x000000' }
    - { index: 18, color: '0x404040' }
    - { index: 19, color: '0x606060' }
    - { index: 20, color: '0x808080' }
    - { index: 21, color: '0xc0c0c0' }

